{% set name = "ipaddr" %}
{% set version = "2.2.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4092dfe667588d16aa12b59acb7c8a4024e5dcb23a681cd0b0b602373eca88d6" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - ipaddr

about:
  home: https://github.com/google/ipaddr-py
  license_file: COPYING
  license: Apache 2.0
  license_family: Apache
  summary: "Google's Python IP address manipulation library"
  dev_url: https://github.com/google/ipaddr-py

extra:
  recipe-maintainers:
    - pmlandwehr
